# Generated by Django 2.0.3 on 2020-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('port', models.IntegerField(default=22, max_length=10, null=True)),
                ('login_user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'ssh信息',
                'db_table': 'SshInfo',
            },
        ),
    ]
